//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public Nullable<int> MedicalCardId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> NurseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual MedicalCard MedicalCard { get; set; }
        public virtual Nurse Nurse { get; set; }
    }
}
