//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polyclinic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentView
    {
        public int Id { get; set; }
        public string Пациент { get; set; }
        public string Врач { get; set; }
        public Nullable<int> Кабинет { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    }
}
